### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by persianpros**
- Add icon for enigma2 plugin
- Add enable/disable feature for use gstreamer libraries or hisilicon libraries in enigma2 players
- Add translation support
- Remove superfluous usage of skin_default in image paths
- Create README.md
- Enable gamma support

Thanks to OpenSPA

### CODE REVIEW

**Comment by Kerberos1864** [comment]
@zgemma-star why you don't merge these  updates ?

**Comment by persianpros** [comment]
There's no need anynore, we have our own version: https://github.com/OpenVisionE2/servicehisilicon

**Comment by Kerberos1864** [comment]
> There's no need anynore, we have our own version: https://github.com/OpenVisionE2/servicehisilicon

But how can I benefit from your updates If I am using openATV ?
Can you elaborate please

**Comment by persianpros** [comment]
You could ask them to use our repo or cherry-pick the goods, I think Zgemma won't.

**Comment by zgemma-star** [comment]
The plugin disables the power of Hisilicon media player. When it was set standard enable it would been probably pass the tests. It's highly recommand to use hisilicon player and not the bad and unsupport gstreamer player

**Pull request closed without merging**
